# Generated by Django 4.1.2 on 2022-10-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0002_book_author_book_is_bestselling_alter_book_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="rating", new_name="ratings",
        ),
    ]
