# Generated by Django 4.1.2 on 2022-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0003_rename_rating_book_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="book", name="slug", field=models.SlugField(default=""),
        ),
    ]
